apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
        - name: demoapp
          image: siddharth20/java-demoapp:1.0.0-23
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
